# report/template.py

REPORT_TEMPLATE = """
# 🛡️ Phantom Scan Report

**Target:** {target_value}    
**Run ID:** {run_id}

---

## 🧾 Summary

{summary}

---

## 🔍 Port Scan (`nmap`)

**Tool:** nmap  

**Findings:**  
{port_scan_summary}

<details>
<summary>View Raw Output</summary>
```
{port_scan_raw}
```
</details>

---

## 🧠 Web Technology Fingerprinting (`whatweb`)

**Tool:** WhatWeb  

**Findings:**  
{web_tech_summary}

<details>
<summary>View Raw Output</summary>
```
{web_tech_raw}
```
</details>

---

## 🌐 DNS Lookup (`dnsrecon`)

**Tool:** DNSRecon  

**Findings:**  
{dns_lookup_summary}

<details>
<summary>View Raw Output</summary>
```
{dns_lookup_raw}
```
</details>

---

## 🕵️ WHOIS Lookup (`whois`)

**Tool:** WHOIS  

**Findings:**  
{whois_summary}

<details>
<summary>View Raw Output</summary>
```
{whois_raw}
```
</details>

---

## 🗂 Directory Enumeration (`gobuster`)

**Tool:** Gobuster  

**Findings:**  
{dir_enum_summary}

<details>
<summary>View Raw Output</summary>
```
{dir_enum_raw}
```
</details>

---

## 🔍 Vulnerability Scan (`wapiti`)

**Tool:** Wapiti  

**Findings:**  
{vuln_scan_summary}

<details>
<summary>View Raw Output</summary>
```
{vuln_scan_raw}
```
</details>

---

**Generated by:** Phantom — Cyber Reconnaissance Tool   
**Report Version:** v1.0

"""


OVERALL_SUMMARY_PROMPT = """
You are a senior cybersecurity analyst.

Your task is to generate an overall executive summary of a reconnaissance scan based on the following tool summaries.

Summarize:
- What type of system is being scanned (web server, mail server, etc.)
- Key findings from the various tools
- Any major vulnerabilities or risks discovered
- General security posture (e.g., secure, misconfigured, vulnerable)

Use clear, concise language appropriate for a technical report.

Tool Summaries:
------------------
{tool_summaries}

Overall Summary:
"""


